[build]
  publish = "build"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  CI = "false" 
  NPM_FLAGS = "--legacy-peer-deps"

# Handle API routes for backend - thebioping.com domain
[[redirects]]
  from = "/api/*"
  to = "https://bioping-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Force cache refresh for all files - CLIENT CACHE BUSTING
[[headers]]
  for = "/*"
  [headers.values]
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

# Allow PDF embedding and set proper headers
[[headers]]
  for = "*.pdf"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Range"

# Force refresh for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

# Force refresh for JS files
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

# Force refresh for CSS files
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

# Force refresh for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0" 