services:
  - type: web
    name: ravan-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        value: gauravvij1980@gmail.com
      - key: EMAIL_PASS
        value: keux xtjd bzat vnzj
      - key: GMAIL_USER
        value: gauravvij1980@gmail.com
      - key: GMAIL_PASS
        value: keux xtjd bzat vnzj
      - key: JWT_SECRET
        value: bioping-super-secure-jwt-secret-key-2025-very-long-and-random-string
      - key: REACT_APP_API_BASE_URL
        value: https://bioping-backend.onrender.com
      - key: STRIPE_SECRET_KEY
        value: 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
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_live_51RlErgLf1iznKy11bUQ4zowN63lhfc2ElpXY9stuz1XqzBBJcWHHWzczvSUfVAxkFQiOTFfzaDzD38WMzBKCAlJA00lB6CGJwT
      - key: REACT_APP_STRIPE_PUBLISHABLE_KEY
        value: pk_live_51RlErgLf1iznKy11bUQ4zowN63lhfc2ElpXY9stuz1XqzBBJcWHHWzczvSUfVAxkFQiOTFfzaDzD38WMzBKCAlJA00lB6CGJwT
      - key: MONGODB_URI
        value: mongodb+srv://gauravvij1980:gauravvij1980@cluster0.8jf4q.mongodb.net/biotech?retryWrites=true&w=majority
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
    healthCheckPath: /api/health
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      - path: /*
        name: Pragma
        value: "no-cache"
      - path: /*
        name: Expires
        value: "0"
      - path: "*.html"
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      - path: "*.js"
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      - path: "*.css"
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      # PDF specific headers for Render
      - path: "*.pdf"
        name: Cache-Control
        value: "public, max-age=3600"
      - path: "*.pdf"
        name: X-Frame-Options
        value: "SAMEORIGIN"
      - path: "*.pdf"
        name: Content-Type
        value: "application/pdf"
      - path: "*.pdf"
        name: Access-Control-Allow-Origin
        value: "*"
      - path: "*.pdf"
        name: Access-Control-Allow-Methods
        value: "GET, HEAD, OPTIONS"
      - path: "*.pdf"
        name: Access-Control-Allow-Headers
        value: "Range"
      # Static files for PDF serving
      - path: "/pdf/*"
        name: Cache-Control
        value: "public, max-age=3600"
      - path: "/pdf/*"
        name: X-Frame-Options
        value: "SAMEORIGIN"
      - path: "/pdf/*"
        name: Content-Type
        value: "application/pdf" 