services:
  - type: web
    name: ravan-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      - path: /*
        name: Pragma
        value: "no-cache"
      - path: /*
        name: Expires
        value: "0"
      - path: "*.html"
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      - path: "*.js"
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      - path: "*.css"
        name: Cache-Control
        value: "no-cache, no-store, must-revalidate, max-age=0"
      # PDF specific headers for Render
      - path: "*.pdf"
        name: Cache-Control
        value: "public, max-age=3600"
      - path: "*.pdf"
        name: X-Frame-Options
        value: "SAMEORIGIN"
      - path: "*.pdf"
        name: Content-Type
        value: "application/pdf"
      - path: "*.pdf"
        name: Access-Control-Allow-Origin
        value: "*"
      - path: "*.pdf"
        name: Access-Control-Allow-Methods
        value: "GET, HEAD, OPTIONS"
      - path: "*.pdf"
        name: Access-Control-Allow-Headers
        value: "Range"
      # Static files for PDF serving
      - path: "/pdf/*"
        name: Cache-Control
        value: "public, max-age=3600"
      - path: "/pdf/*"
        name: X-Frame-Options
        value: "SAMEORIGIN"
      - path: "/pdf/*"
        name: Content-Type
        value: "application/pdf" 