name: Keep Render Awake

on:
  schedule:
    # Every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Ping Render health endpoint(s)
        shell: bash
        run: |
          set -e
          URLS=(
            "https://bioping-backend.onrender.com/api/health"
            "https://ravan-backend.onrender.com/api/health"
            "https://bioping-server.onrender.com/api/health"
          )
          for url in "${URLS[@]}"; do
            echo "Pinging $url"
            # Try HEAD first; fall back to GET
            if ! curl -fsS -o /dev/null -X HEAD "$url"; then
              curl -fsS -o /dev/null "$url"
            fi
          done


